

[vm_service]
vm-service ansible_host=192.168.56.10




[control_plane]
control-plane ansible_host=192.168.56.11



[workers]
worker-1 ansible_host=192.168.56.12
worker-2 ansible_host=192.168.56.13



# Groupe global du cluster Kubernetes 
[k8s_cluster:children]
control_plane
workers


# Groupe "all_vms" : absolument toutes les VM
[all_vms:children]
vm_service
k8s_cluster


# Variables globales pour toutes les machines
[all:vars]
# Python
ansible_python_interpreter=/usr/bin/python3
# utilisateur SSH
ansible_user=vagrant               
# clé SSH privée       
ansible_ssh_private_key_file=~/.ssh/ansible_key 
# ignorer la confirmation SSH
ansible_ssh_common_args='-o StrictHostKeyChecking=no'  


